version: "3.8"

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    networks:
      - chromanet
    volumes:
      - ./chroma_db_data:/chroma/chroma  

networks:
  chromanet:
    driver: bridge
